In [2]:
import numpy as np

In [3]:
index = np.array([[0, 1, 2, 0], [0, 1, 4, 2], [0, 0, 3, 0]])    # index矩阵里存放的是A矩阵的索引
A = np.array([[0.12, 0.15, 0.98],
                  [0.10, 0.65, 0.23],
                  [0.45, 0.56, 0.23],
                  [0.40, 0.82, 0.41],
                  [0.35, 0.89, 0.18],
                  [0.45, 0.21, 0.82],
                  [0.78, 0.12, 0.63]])

In [5]:
index

array([[0, 1, 2, 0],
       [0, 1, 4, 2],
       [0, 0, 3, 0]])

In [10]:
A

array([[0.12, 0.15, 0.98],
       [0.1 , 0.65, 0.23],
       [0.45, 0.56, 0.23],
       [0.4 , 0.82, 0.41],
       [0.35, 0.89, 0.18],
       [0.45, 0.21, 0.82],
       [0.78, 0.12, 0.63]])

In [7]:
A[index]

array([[[0.12, 0.15, 0.98],
        [0.1 , 0.65, 0.23],
        [0.45, 0.56, 0.23],
        [0.12, 0.15, 0.98]],

       [[0.12, 0.15, 0.98],
        [0.1 , 0.65, 0.23],
        [0.35, 0.89, 0.18],
        [0.45, 0.56, 0.23]],

       [[0.12, 0.15, 0.98],
        [0.12, 0.15, 0.98],
        [0.4 , 0.82, 0.41],
        [0.12, 0.15, 0.98]]])

In [9]:
a = np.array([[[0.12, 0.15, 0.98], [0.10, 0.65, 0.23], [0.45, 0.56, 0.23], [0.12, 0.15, 0.98]],
                  [[0.12, 0.15, 0.98], [0.10, 0.65, 0.23], [0.35, 0.89, 0.18], [0.45, 0.56, 0.23]],
                  [[0.12, 0.15, 0.98], [0.12, 0.15, 0.98], [0.40, 0.82, 0.41], [0.12, 0.15, 0.98]]])
a

array([[[0.12, 0.15, 0.98],
        [0.1 , 0.65, 0.23],
        [0.45, 0.56, 0.23],
        [0.12, 0.15, 0.98]],

       [[0.12, 0.15, 0.98],
        [0.1 , 0.65, 0.23],
        [0.35, 0.89, 0.18],
        [0.45, 0.56, 0.23]],

       [[0.12, 0.15, 0.98],
        [0.12, 0.15, 0.98],
        [0.4 , 0.82, 0.41],
        [0.12, 0.15, 0.98]]])

In [8]:
torch_data = torch.from_numpy(a)